name: Deploy
  
on: [push, pull_request]

jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
   
    name: Deploying to Github Pages

    steps:
      - name: Checkout Codes
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install packages
        run: yarn install
      
      - name: Set Creds
        run: |
          git config user.name "curder"
          git config user.email "q.curder@gmail.com"
      
      - name: Deploy
        run: yarn deploy