name: Deploy to Github Pages
  on: [push, pull_request]

jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codes
        - uses: actions/checkout@v2

      - name: Setup Node
        - uses: actions/setup-node@v2
          with:
            node-version: '15'

      - name: Install packages
        run: yarn install
      
      - name: Set Creds
        run: |
          git config user.name "curder"
          git config user.email "q.curder@gmail.com"
      
      - name: Deploy
        run: yarn deploy